version: 2

run:
  timeout: 5m
  skip-dirs:
    - generated
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # Exclude generated files from all linters
    - path: generated/
      linters:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - misspell
        - gocritic
        - gosec
        - unconvert
        - prealloc
        - exportloopref
        - bodyclose
        - noctx
