name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of SpaceTraders MCP Server are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      options:
        - Linux
        - macOS
        - Windows
        - Docker
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: go-version
    attributes:
      label: Go Version (if building from source)
      description: What version of Go are you using?
      options:
        - "1.24"
        - "1.22"
        - "1.21"
        - "1.20"
        - "Not applicable (using binary)"
        - Other (please specify in description)
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. Send request '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        Please share your configuration (remove any sensitive information like API tokens):
        - Claude Desktop config
        - Environment variables
        - .env file contents (redacted)
      render: json
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. Screenshots, error messages, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please check all that apply
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have included all relevant information requested above
          required: true
        - label: I have tested with the latest version
          required: false
        - label: I have redacted any sensitive information (API tokens, personal data)
          required: true
